# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bython.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QTextEdit, QWidget, QStatusBar, QAction


class grande_fenetre_principale(object):
    
    def creation(self, fenetre_principale):
        
        fenetre_principale.setObjectName("fenetre_principale")
        fenetre_principale.resize(935, 598)
        
        self.centralwidget = QtWidgets.QWidget(fenetre_principale)
        self.centralwidget.setObjectName("centralwidget")
        
        #--------- création du  tabwidget -----------------------------------################################
        
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1700, 141))
        self.tabWidget.setObjectName("tabWidget")
        ########################################################################
        
        #--------- création des deux widgets de mon tabwidget ----------------------------------
        
        self.tab_Accueil = QtWidgets.QWidget()
        self.tab_Accueil.setObjectName("tab_Accueil")
        self.tabWidget.addTab(self.tab_Accueil, "")
        
        self.tab_affichage = QtWidgets.QWidget()
        self.tab_affichage.setObjectName("tab_affichage")
        self.tabWidget.addTab(self.tab_affichage, "")
        ########################################################################
        
        #--------- création du frame de tab_Accueil  -----------------------------------################################
        
        self.frame = QtWidgets.QFrame(self.tab_Accueil)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 1001, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        #######################################################################
        
        #--------- création des boutons push et labels du frame -----------------------------------
        
        #---------------  Pour presse papier    ----------------------------------------------------
        self.pushButton_coller = QtWidgets.QPushButton(self.frame)
        self.pushButton_coller.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.pushButton_coller.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_coller.setIcon(icon)
        self.pushButton_coller.setIconSize(QtCore.QSize(58, 57))
        self.pushButton_coller.setObjectName("pushButton_coller")
        ##
        self.label_coller = QtWidgets.QLabel(self.frame)
        self.label_coller.setGeometry(QtCore.QRect(10, 70, 49, 16))
        self.label_coller.setObjectName("label_coller")        
        
        self.pushButton_couper = QtWidgets.QPushButton(self.frame)
        self.pushButton_couper.setGeometry(QtCore.QRect(70, 10, 75, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_couper.setIcon(icon1)
        self.pushButton_couper.setObjectName("pushButton_3")
        
        self.pushButton_copier = QtWidgets.QPushButton(self.frame)
        self.pushButton_copier.setGeometry(QtCore.QRect(70, 40, 75, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_copier.setIcon(icon2)
        self.pushButton_copier.setObjectName("pushButton_copier")
        
        self.label_presse_papier = QtWidgets.QLabel(self.frame)
        self.label_presse_papier.setGeometry(QtCore.QRect(30, 90, 81, 20))
        self.label_presse_papier.setObjectName("label_presse_papier")        
        ######################################################################
        
        # ----------------------- pour label_police -----------------------------------------
        
        self.pushButton_surbrillance = QtWidgets.QPushButton(self.frame)
        self.pushButton_surbrillance.setGeometry(QtCore.QRect(260, 10, 41, 41))
        self.pushButton_surbrillance.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/surbrillance.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)        
        self.pushButton_surbrillance.setIcon(icon3)
        self.pushButton_surbrillance.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_surbrillance.setObjectName("pushButton_surbrillance")
        
        self.pushButton_couleur = QtWidgets.QPushButton(self.frame)
        self.pushButton_couleur.setGeometry(QtCore.QRect(160, 10, 41, 41))
        self.pushButton_couleur.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_couleur.setIcon(icon4)
        self.pushButton_couleur.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_couleur.setObjectName("pushButton_couleur")
        
        self.pushButton_font = QtWidgets.QPushButton(self.frame)
        self.pushButton_font.setGeometry(QtCore.QRect(210, 10, 41, 41))
        self.pushButton_font.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Images/font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_font.setIcon(icon16)
        self.pushButton_font.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_font.setObjectName("pushButton_font")        
        
        self.label_police = QtWidgets.QLabel(self.frame)
        self.label_police.setGeometry(QtCore.QRect(220, 80, 61, 20))
        self.label_police.setObjectName("label_police")
        ########################################################################################
        
        # ----------------------- pour label_paragraphe -----------------------------------------
        
        self.pushButton_justifyLeft = QtWidgets.QPushButton(self.frame)
        self.pushButton_justifyLeft.setGeometry(QtCore.QRect(320, 10, 41, 41))
        self.pushButton_justifyLeft.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Images/justifyLeft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_justifyLeft.setIcon(icon10)
        self.pushButton_justifyLeft.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_justifyLeft.setObjectName("pushButton_justifyLeft")
        
        self.pushButton_justifyCenter = QtWidgets.QPushButton(self.frame)
        self.pushButton_justifyCenter.setGeometry(QtCore.QRect(370, 10, 41, 41))
        self.pushButton_justifyCenter.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Images/justifyCenter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_justifyCenter.setIcon(icon11)
        self.pushButton_justifyCenter.setIconSize(QtCore.QSize(40, 407))
        self.pushButton_justifyCenter.setObjectName("pushButton_justifyCenter")
        
        self.pushButton_justifyRight = QtWidgets.QPushButton(self.frame)
        self.pushButton_justifyRight.setGeometry(QtCore.QRect(420, 10, 41, 41))
        self.pushButton_justifyRight.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Images/justifyRight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_justifyRight.setIcon(icon12)
        self.pushButton_justifyRight.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_justifyRight.setObjectName("pushButton_justifyRight")
        
        self.label_paragraphe = QtWidgets.QLabel(self.frame)
        self.label_paragraphe.setGeometry(QtCore.QRect(360, 80, 71, 16))
        self.label_paragraphe.setObjectName("label_paragraphe")
        #######################################################################################
        
        # ----------------------- pour label_image -----------------------------------------
        
        self.pushButton_insert_image = QtWidgets.QPushButton(self.frame)
        self.pushButton_insert_image.setGeometry(QtCore.QRect(490, 10, 41, 41))
        self.pushButton_insert_image.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Images/insert_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_insert_image.setIcon(icon13)
        self.pushButton_insert_image.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_insert_image.setObjectName("pushButton_insert_image")
        ##
        self.label_image = QtWidgets.QLabel(self.frame)
        self.label_image.setGeometry(QtCore.QRect(500, 60, 41, 16))
        self.label_image.setObjectName("label_image")        
        #############################################################################################"
        
        # ----------------------- pour label_Dessin_paint -----------------------------------------
        
        self.pushButton_paint = QtWidgets.QPushButton(self.frame)
        self.pushButton_paint.setGeometry(QtCore.QRect(640, 10, 41, 41))
        self.pushButton_paint.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Images/pngegg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_paint.setIcon(icon14)
        self.pushButton_paint.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_paint.setObjectName("pushButton_paint")
        ##
        self.label_Dessin_paint = QtWidgets.QLabel(self.frame)
        self.label_Dessin_paint.setGeometry(QtCore.QRect(640, 60, 71, 20))
        self.label_Dessin_paint.setObjectName("label_Dessin_paint")
        ##################################################################################################
        
        # ----------------------- pour label_recherche -----------------------------------------
        
        self.pushButton_recherche = QtWidgets.QPushButton(self.frame)
        self.pushButton_recherche.setGeometry(QtCore.QRect(730, 10, 41, 41))
        self.pushButton_recherche.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Images/pngegg (9).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_recherche.setIcon(icon15)
        self.pushButton_recherche.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_recherche.setObjectName("pushButton_recherche")
        ##
        self.label_recherche = QtWidgets.QLabel(self.frame)
        self.label_recherche.setGeometry(QtCore.QRect(720, 60, 71, 20))
        self.label_recherche.setObjectName("label_recherche")
        ####################################################################################################
        
        self.pushButton_date_et_heure = QtWidgets.QPushButton(self.frame)
        self.pushButton_date_et_heure.setGeometry(QtCore.QRect(556, 10, 37, 35))
        self.pushButton_date_et_heure.setText("")
        icon0 = QtGui.QIcon()
        icon0.addPixmap(QtGui.QPixmap("Images/Horloge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)        
        self.pushButton_date_et_heure.setIcon(icon0)
        self.pushButton_date_et_heure.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_date_et_heure.setObjectName("pushButton_date_et_heure")
        ##
        self.label_Date_heure = QtWidgets.QLabel(self.frame)
        self.label_Date_heure.setGeometry(QtCore.QRect(550, 60, 71, 16))
        self.label_Date_heure.setObjectName("label_Date_heure")        
        
        self.label_insertion = QtWidgets.QLabel(self.frame)
        self.label_insertion.setGeometry(QtCore.QRect(560, 90, 71, 16))
        self.label_insertion.setObjectName("label_insertion")
        #######################################################################################"###############################""#################
        
        
        
        # ------------------ les pushbuttons de tab affichage ------------------------------------------
        
        self.pushButton_close = QtWidgets.QPushButton(self.tab_affichage)
        self.pushButton_close.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.pushButton_close.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon17)
        self.pushButton_close.setIconSize(QtCore.QSize(43, 44))
        self.pushButton_close.setObjectName("pushButton_close")
        
        self.pushButton_pdf = QtWidgets.QPushButton(self.tab_affichage)
        self.pushButton_pdf.setGeometry(QtCore.QRect(90, 20, 51, 41))
        self.pushButton_pdf.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Images/pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_pdf.setIcon(icon18)
        self.pushButton_pdf.setIconSize(QtCore.QSize(43, 44))
        self.pushButton_pdf.setObjectName("pushButton_pdf")
        
        self.pushButton_zoom_moins = QtWidgets.QPushButton(self.tab_affichage)
        self.pushButton_zoom_moins.setGeometry(QtCore.QRect(240, 20, 51, 41))
        self.pushButton_zoom_moins.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("Images/zoom_moins.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)        
        self.pushButton_zoom_moins.setIcon(icon30)
        self.pushButton_zoom_moins.setIconSize(QtCore.QSize(43, 44))
        self.pushButton_zoom_moins.setObjectName("pushButton_zoom_moins")
        
        self.pushButton_zoom_plus = QtWidgets.QPushButton(self.tab_affichage)
        self.pushButton_zoom_plus.setGeometry(QtCore.QRect(160, 20, 51, 41))
        self.pushButton_zoom_plus.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("Images/zoom_plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)        
        self.pushButton_zoom_plus.setIcon(icon31)
        self.pushButton_zoom_plus.setIconSize(QtCore.QSize(43, 44))
        self.pushButton_zoom_plus.setObjectName("pushButton_zoom_plus")
        ########################################################################
        
        
        #--------- création de QTextEdit -----------------------------------
        
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(63, 150, 1800, 790))
        self.textEdit.setObjectName("textEdit")
        
        fenetre_principale.setCentralWidget(self.centralwidget)
        
        #--------- création de la barre d'outils -----------------------------------
        
        self.toolBar = QtWidgets.QToolBar(fenetre_principale)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.toolBar.setFont(font)
        self.toolBar.setObjectName("toolBar")
        fenetre_principale.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        
        #--------- création de la barre d'état -----------------------------------
        
        self.statusBar = QtWidgets.QStatusBar(fenetre_principale)
        self.statusBar.setObjectName("statusBar")
        fenetre_principale.setStatusBar(self.statusBar)
        
        #--------- création de la barre de menu -----------------------------------
        
        self.ma_barre_de_menu = QtWidgets.QMenuBar(fenetre_principale)
        self.ma_barre_de_menu.setEnabled(True)
        self.ma_barre_de_menu.setGeometry(QtCore.QRect(0, 0, 935, 22))
        self.ma_barre_de_menu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ma_barre_de_menu.setDefaultUp(False)
        self.ma_barre_de_menu.setNativeMenuBar(True)
        self.ma_barre_de_menu.setObjectName("menuBar")
        
        self.sous_menu = QtWidgets.QMenu(self.ma_barre_de_menu)
        self.sous_menu.setEnabled(True)
        self.sous_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sous_menu.setAutoFillBackground(False)
        self.sous_menu.setTearOffEnabled(False)
        self.sous_menu.setSeparatorsCollapsible(False)
        self.sous_menu.setToolTipsVisible(False)
        self.sous_menu.setObjectName("sous menu")
        
        # ---------- sous menu imprimer ----------------------------------
        
        self.sous_menu_imprimer = QtWidgets.QMenu(self.sous_menu)
        self.sous_menu_imprimer.setObjectName("sous menu imprimer")
        fenetre_principale.setMenuBar(self.ma_barre_de_menu)
        ##
        
        # --------------------- création des QAction ---------------
        
        self.actionnouveau = QtWidgets.QAction(fenetre_principale)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Images/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnouveau.setIcon(icon19)
        self.actionnouveau.setObjectName("actionnouveau")
        
        self.actionsauvegarder = QtWidgets.QAction(fenetre_principale)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsauvegarder.setIcon(icon20)
        self.actionsauvegarder.setObjectName("actionsauvegarder")
        
        self.actionEnregistrer_Sous = QtWidgets.QAction(fenetre_principale)
        self.actionEnregistrer_Sous.setIcon(icon20)
        self.actionEnregistrer_Sous.setObjectName("actionEnregistrer_Sous")        
        
        self.actionundo = QtWidgets.QAction(fenetre_principale)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("Images/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionundo.setIcon(icon21)
        self.actionundo.setObjectName("actionundo")
        
        self.actionredo = QtWidgets.QAction(fenetre_principale)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("Images/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionredo.setIcon(icon22)
        self.actionredo.setObjectName("actionredo")
        
        self.actionouvrir = QtWidgets.QAction(fenetre_principale)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("Images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionouvrir.setIcon(icon23)
        self.actionouvrir.setObjectName("actionouvrir")
        
        self.actionA_propos = QtWidgets.QAction(fenetre_principale)
        self.actionA_propos.setObjectName("actionA_propos")
        
        self.actionQuitter = QtWidgets.QAction(fenetre_principale)
        self.actionQuitter.setObjectName("actionQuitter")
        
        self.actionemail = QtWidgets.QAction(fenetre_principale)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("Images/mail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionemail.setIcon(icon26)
        self.actionemail.setObjectName("actionemail")
        
        self.actionimprimer = QtWidgets.QAction(fenetre_principale)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("Images/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionimprimer.setIcon(icon25)
        self.actionimprimer.setObjectName("actionimprimer")
        
        self.actionprevisualisation = QtWidgets.QAction(fenetre_principale)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("Images/preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionprevisualisation.setIcon(icon24)
        self.actionprevisualisation.setObjectName("actionprevisualisation")
        ####################################################################################
        
        # ------------ Ajout des actions à la barre d'outils ------------------------------------
        
        self.toolBar.addAction(self.actionsauvegarder)
        self.toolBar.addAction(self.actionundo)
        self.toolBar.addAction(self.actionredo)
        self.toolBar.addAction(self.actionnouveau)
        self.toolBar.addAction(self.actionouvrir)
        
        self.toolBar.addSeparator()
        
        self.toolBar.addAction(self.actionemail)
        self.toolBar.addAction(self.actionimprimer)
        self.toolBar.addAction(self.actionprevisualisation)
        ###################################################
        
        # ------------ Ajout des actions à la barre de menu ------------------------------------
        
        self.sous_menu.addAction(self.actionnouveau)
        self.sous_menu.addAction(self.actionouvrir)
        self.sous_menu.addAction(self.actionsauvegarder)
        self.sous_menu.addAction(self.actionEnregistrer_Sous)
        
        self.sous_menu.addSeparator()
        
        self.sous_menu_imprimer.addAction(self.actionprevisualisation)
        self.sous_menu_imprimer.addAction(self.actionimprimer)
        self.sous_menu.addAction(self.sous_menu_imprimer.menuAction())
        
        self.sous_menu.addSeparator()
        
        self.sous_menu.addAction(self.actionA_propos)
        self.sous_menu.addAction(self.actionQuitter)
        
        self.sous_menu.addSeparator()
        
        self.ma_barre_de_menu.addAction(self.sous_menu.menuAction())
        #################################################
        
        #c'est grâce au code ci-dessous que la méthode traduction fonctionne c-a-d lorsque la souris passe sur chaque 
        #icône, on a une info-bulle

        self.traduction(fenetre_principale)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(fenetre_principale)

    def traduction(self, fenetre_principale):
        
        _translate = QtCore.QCoreApplication.translate
        fenetre_principale.setWindowTitle(_translate("fenetre_principale", "fenetre_principale"))
        
        # nom des elements de tab widgets pour afficher
        
        self.pushButton_pdf.setText(_translate("fenetre_principale", ""))
        self.pushButton_pdf.setToolTip(_translate("fenetre_principale", "convertir le texte en pdf"))
        
        self.pushButton_close.setText(_translate("fenetre_principale", ""))
        self.pushButton_close.setToolTip(_translate("fenetre_principale", "tout effacer"))
        
        self.pushButton_zoom_plus.setText(_translate("fenetre_principale", ""))
        self.pushButton_zoom_plus.setToolTip(_translate("fenetre_principale", "zoomer"))
        
        self.pushButton_zoom_moins.setText(_translate("fenetre_principale", ""))
        self.pushButton_zoom_moins.setToolTip(_translate("fenetre_principale", "dézoomer"))        
        ###############################################################################
    
        # nom des elements de tab widgets accueil
        
        self.pushButton_couper.setText(_translate("fenetre_principale", "Couper"))
        self.pushButton_couper.setToolTip(_translate("fenetre_principale", ""))
        
        self.pushButton_couleur.setText(_translate("fenetre_principale", ""))
        self.pushButton_couleur.setToolTip(_translate("fenetre_principale", "choisir la couleur du texte"))
        
        self.pushButton_font.setText(_translate("fenetre_principale", ""))
        self.pushButton_font.setToolTip(_translate("fenetre_principale", "changer la police, la taille, souligner, surligner,\n mettre en gras et en italic"))        
        
        self.pushButton_surbrillance.setText(_translate("fenetre_principale", ""))
        self.pushButton_surbrillance.setToolTip(_translate("fenetre_principale", "mettre le texte en surbrillance"))
        
        self.pushButton_justifyLeft.setText(_translate("fenetre_principale", ""))
        self.pushButton_justifyLeft.setToolTip(_translate("fenetre_principale", "decaler à gauche"))
        
        self.pushButton_justifyCenter.setText(_translate("fenetre_principale", ""))
        self.pushButton_justifyCenter.setToolTip(_translate("fenetre_principale", "decaler au centre"))
        
        self.pushButton_justifyRight.setText(_translate("fenetre_principale", ""))
        self.pushButton_justifyRight.setToolTip(_translate("fenetre_principale", "decaler à droite"))        
        
        self.pushButton_recherche.setText(_translate("fenetre_principale", ""))
        self.pushButton_recherche.setToolTip(_translate("fenetre_principale", "rechercher du texte"))
        
        self.pushButton_insert_image.setText(_translate("fenetre_principale", ""))
        self.pushButton_insert_image.setToolTip(_translate("fenetre_principale", "insérer une image"))
        
        self.pushButton_paint.setText(_translate("fenetre_principale", ""))
        self.pushButton_paint.setToolTip(_translate("fenetre_principale", "ouvrir paint"))
        
        self.pushButton_date_et_heure.setText(_translate("fenetre_principale", ""))
        self.pushButton_date_et_heure.setToolTip(_translate("fenetre_principale", "insérer la date et l'heure"))        
        
        ###############################################################################
        
        self.label_coller.setText(_translate("fenetre_principale", "Coller"))
        self.pushButton_copier.setText(_translate("fenetre_principale", "Copier"))
        
        self.label_presse_papier.setText(_translate("fenetre_principale", "Presse-papiers"))
        self.label_police.setText(_translate("fenetre_principale", "Police"))
        self.label_paragraphe.setText(_translate("fenetre_principale", "Paragraphe"))
        self.label_insertion.setText(_translate("fenetre_principale", "Insertion"))
        self.label_image.setText(_translate("fenetre_principale", "Image"))
        self.label_Dessin_paint.setText(_translate("fenetre_principale", "Dessin paint"))
        self.label_Date_heure.setText(_translate("fenetre_principale", "Date et heure"))
        
        # nom des tab widgets     
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Accueil), _translate("fenetre_principale", "Accueil"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_affichage), _translate("fenetre_principale", "Affichage"))
        
        self.toolBar.setWindowTitle(_translate("fenetre_principale", "toolBar"))
        
        self.sous_menu.setTitle(_translate("fenetre_principale", "Fichier"))
        self.sous_menu_imprimer.setTitle(_translate("fenetre_principale", "Imprimer"))
        
        self.actionnouveau.setText(_translate("fenetre_principale", "nouveau"))
        self.actionnouveau.setToolTip(_translate("fenetre_principale", "nouveau fichier"))
        self.actionnouveau.setShortcut(_translate("fenetre_principale", "Ctrl+N"))
        
        self.actionsauvegarder.setText(_translate("fenetre_principale", "Enregistrer"))
        self.actionsauvegarder.setToolTip(_translate("fenetre_principale", "sauvegarder"))
        self.actionsauvegarder.setShortcut(_translate("fenetre_principale", "Ctrl+S"))
        
        self.actionundo.setText(_translate("fenetre_principale", "undo"))
        self.actionundo.setToolTip(_translate("fenetre_principale", "undo"))
        self.actionundo.setShortcut(_translate("fenetre_principale", "Ctrl+Z"))
        
        self.actionredo.setText(_translate("fenetre_principale", "redo"))
        self.actionredo.setToolTip(_translate("fenetre_principale", "redo"))
        self.actionredo.setShortcut(_translate("fenetre_principale", "Ctrl+Alt+Z"))
        
        self.actionouvrir.setText(_translate("fenetre_principale", "ouvrir"))
        self.actionouvrir.setToolTip(_translate("fenetre_principale", "ouvrir fichier"))
        self.actionouvrir.setShortcut(_translate("fenetre_principale", "Ctrl+O"))
        
        self.actionA_propos.setText(_translate("fenetre_principale", "A propos"))
        self.actionQuitter.setText(_translate("fenetre_principale", "Quitter"))
        
        self.actionemail.setText(_translate("fenetre_principale", "email"))
        self.actionemail.setToolTip(_translate("fenetre_principale", "envoyer un mail"))
        
        self.actionimprimer.setText(_translate("fenetre_principale", "imprimer"))
        self.actionimprimer.setToolTip(_translate("fenetre_principale", "impression rapide"))
        self.actionimprimer.setShortcut(_translate("fenetre_principale", "Ctrl+P"))
        
        self.actionprevisualisation.setText(_translate("fenetre_principale", "aperçu"))
        self.actionprevisualisation.setToolTip(_translate("fenetre_principale", "aperçu avant impression"))
        self.actionprevisualisation.setShortcut(_translate("fenetre_principale", "Ctrl+Alt+P"))
        
        
        self.actionEnregistrer_Sous.setText(_translate("fenetre_principale", "Enregistrer sous"))
        self.actionEnregistrer_Sous.setToolTip(_translate("fenetre_principale", "Enregistrer sous"))
        self.actionEnregistrer_Sous.setShortcut(_translate("fenetre_principale", "Ctrl+Alt+S"))        
